import json
from fpdf import FPDF
from database import get_db
from threat_intel import enrich_ip
import os
import time

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_pdf_report(alert_id: int) -> str:
    """Generate a PDF intelligence report for an alert. Returns the file path."""

    with get_db() as conn:
        cur = conn.execute("SELECT * FROM alerts WHERE id = ?", (alert_id,))
        alert = cur.fetchone()
        if not alert:
            return None
        alert = dict(alert)

        cur = conn.execute("SELECT * FROM logs WHERE source_ip = ? ORDER BY timestamp ASC", (alert["attacker_ip"],))
        logs = [dict(r) for r in cur.fetchall()]

        cur = conn.execute("SELECT * FROM responses WHERE alert_id = ? OR target = ? ORDER BY timestamp ASC", (alert_id, alert["attacker_ip"]))
        responses = [dict(r) for r in cur.fetchall()]

    enrichment = enrich_ip(alert["attacker_ip"])

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, "ShieldAI SOC - Intelligence Report", ln=True, align="C")
    pdf.ln(5)

    # Alert Info Box
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    title_text = f"Alert: {alert['title']}".encode('latin-1', 'ignore').decode('latin-1')
    pdf.cell(0, 10, title_text, ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    _add_field(pdf, "Alert ID", str(alert["id"]))
    _add_field(pdf, "Timestamp", str(alert["timestamp"]))
    _add_field(pdf, "Attacker IP", alert["attacker_ip"])
    _add_field(pdf, "Severity", alert["severity"])
    _add_field(pdf, "Attack Type", alert.get("attack_type", "N/A"))
    _add_field(pdf, "Verdict", alert.get("verdict", "PENDING"))
    pdf.ln(5)

    # Threat Intelligence
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Threat Intelligence Enrichment", ln=True)
    pdf.set_font("Helvetica", "", 10)
    _add_field(pdf, "Country", f"{enrichment.get('country', 'N/A')} ({enrichment.get('country_code', '')})")
    _add_field(pdf, "ISP", enrichment.get("isp", "N/A"))
    _add_field(pdf, "Abuse Score", f"{enrichment.get('abuse_score', 'N/A')}/100")
    _add_field(pdf, "Usage Type", enrichment.get("usage_type", "N/A"))
    _add_field(pdf, "Source", enrichment.get("source", "N/A"))
    pdf.ln(5)

    # AI Triage Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "AI Triage Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    summary_text = alert.get("llm_summary", "N/A").encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 6, summary_text)
    pdf.ln(5)

    # Evidence
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Evidence", ln=True)
    pdf.set_font("Helvetica", "", 9)
    evidence = json.loads(alert.get("evidence", "{}"))
    for key, val in evidence.items():
        _add_field(pdf, key, str(val))
    pdf.ln(5)

    # Attack Timeline
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Attack Timeline ({len(logs)} events)", ln=True)
    pdf.set_font("Courier", "", 8)
    for log in logs[:30]:  # Limit to 30 for readability
        line = f"{log['timestamp']} | {log['event_type']} | {log['source_ip']} | {log.get('user_id', '-')} | {log['status']}"
        line = line.encode('latin-1', 'ignore').decode('latin-1')
        pdf.cell(0, 5, line, ln=True)
    if len(logs) > 30:
        pdf.cell(0, 5, f"... and {len(logs) - 30} more events", ln=True)
    pdf.ln(5)

    # Response Actions
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Autonomous Response Actions ({len(responses)})", ln=True)
    pdf.set_font("Helvetica", "", 9)
    for resp in responses:
        _add_field(pdf, resp["action_type"], f"Target: {resp['target']} at {resp['timestamp']}")
    pdf.ln(5)

    # Full Attacker Report
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Full Attacker Intelligence Report", ln=True)
    pdf.set_font("Helvetica", "", 9)
    report_text = alert.get("attacker_report", "No report available.")
    # Clean markdown for PDF
    clean_text = report_text.replace("##", "").replace("**", "").replace("###", "").replace("---", "").replace("—", "-")
    clean_text = clean_text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 5, clean_text)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 5, "Generated by ShieldAI SOC Platform - Confidential", ln=True, align="C")

    filename = f"report_alert_{alert_id}_{int(time.time())}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    return filepath


def _add_field(pdf, label, value):
    pdf.set_font("Helvetica", "B", 10)
    label = label.encode('latin-1', 'ignore').decode('latin-1')
    value = value.encode('latin-1', 'ignore').decode('latin-1')
    pdf.cell(50, 6, f"{label}:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, value, ln=True)
