import os
import time
from fpdf import FPDF
from database import get_db

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

def generate_threat_intel_report() -> str:
    """Generate a PDF intelligence report summarizing the current threat landscape."""

    with get_db() as conn:
        # Fetch latest CISA KEVs
        cur = conn.execute("SELECT * FROM cisa_kev ORDER BY date_added DESC LIMIT 10")
        kevs = [dict(r) for r in cur.fetchall()]

        # Fetch tracked general CVEs
        cur = conn.execute("SELECT * FROM cve_feed ORDER BY published_date DESC LIMIT 10")
        cves = [dict(r) for r in cur.fetchall()]

        # Fetch active IP blocks to correlate with threat intel
        cur = conn.execute(
            "SELECT target, action_type, timestamp FROM responses "
            "WHERE action_type IN ('TEMP_BLOCK', 'PERM_BLOCK') AND status = 'ACTIVE' "
            "ORDER BY timestamp DESC LIMIT 20"
        )
        blocks = [dict(r) for r in cur.fetchall()]

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, "ShieldAI SOC - Threat Intelligence Report", ln=True, align="C")
    pdf.ln(5)
    
    # Executive Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Executive Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    summary = f"This report outlines the current threat landscape, including {len(kevs)} newly added Known Exploited Vulnerabilities (KEVs), {len(cves)} tracked high-severity CVEs, and recent autonomous blocking actions against malicious IPs."
    pdf.multi_cell(0, 6, summary)
    pdf.ln(5)

    # CISA KEVs
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 200, 200)
    pdf.cell(0, 10, "CISA Known Exploited Vulnerabilities (KEV)", ln=True, fill=True)
    pdf.ln(3)
    
    for kev in kevs:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, f"{kev['cve_id']} - {kev['vulnerability_name']}".encode('latin-1', 'ignore').decode('latin-1'), ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"Date Added: {kev['date_added']} | Vendor: {kev['vendor_project']}", ln=True)
        desc = kev['short_description'].encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 5, f"Description: {desc}")
        pdf.ln(3)

    pdf.add_page()

    # General CVEs
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 200)
    pdf.cell(0, 10, "Tracked High-Severity CVEs", ln=True, fill=True)
    pdf.ln(3)
    
    for cve in cves:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, f"{cve['cve_id']} - {cve['severity']} (CVSS: {cve['cvss_score']})", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"Published: {cve['published_date']}", ln=True)
        desc = cve['description'].encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 5, f"Description: {desc}")
        pdf.ln(3)

    pdf.ln(5)

    # IP Blocks
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(200, 200, 240)
    pdf.cell(0, 10, "Recent Autonomous Blocks", ln=True, fill=True)
    pdf.ln(3)
    
    pdf.set_font("Courier", "", 9)
    for block in blocks:
        line = f"{block['timestamp']} | {block['action_type']} | {block['target']}"
        pdf.cell(0, 5, line, ln=True)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 5, "Generated by ShieldAI SOC Platform - Confidential Threat Intel", ln=True, align="C")

    filename = f"threat_intel_report_{int(time.time())}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    return filepath
