apiVersion: v1
kind: Service
metadata:
  name: soc-backend
spec:
  selector:
    app: soc-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: soc-frontend
spec:
  selector:
    app: soc-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the frontend to external traffic
