apiVersion: v1
kind: Service
metadata:
  name: {{ include "edysor.fullname" . }}-backend
  labels:
    app: edysor-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: edysor-backend
  type: {{ .Values.service.backend.type }}
