apiVersion: v1
kind: Service
metadata:
  name: {{ include "edysor.fullname" . }}-frontend
  labels:
    app: edysor-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: edysor-frontend
  type: {{ .Values.service.frontend.type }}
