apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: edysor-agent-scaler
  namespace: edysor-soc
spec:
  scaleTargetRef:
    name: edysor-core
  minReplicaCount: 3
  maxReplicaCount: 50
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-cluster:9092
      consumerGroup: edysor-ingest
      topic: raw-telemetry
      # Scale out if lag exceeds 1000 logs
      lagThreshold: "1000"
