apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edysor-soc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/akshat2685/ai-soc-mvp.git' # Repository URL
    targetRevision: HEAD
    path: k8s/helm-charts/edysor # Path to Helm chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
